### ISSUE TITLE
Clarify platform-specific “registers”

### ISSUE THREAD

**Issue by pdp7** [riscv-non-isa/riscv-acpi-ffh#10]
From section 2:
> Resource descriptors, which are formatted per the “Generic Register Descriptor” definition ([ACPI 6.5] section 6.4.3.7, also see ASL Register in section 19.6.114), are used by ACPI tables to **provide the OSPM read and/or write access to platform-specific “registers”.** A resource descriptor may be a fixed value, hardware address, function or function parameter identifier, or any other encoding of its bits. While encodings are specific to their applications, RISC-V uses a common top-level encoding whenever possible.

I'm new to ACPI and I'm trying to understand the nature of ACPI registers.  I noticed in the phrase `platform-specific “registers”` that registers is in quotes.  Is it expected that a RISC-V SoC would have memory mapped registers for the ACPI CPPC registers?

I am confused about how the 0x7F (FFixedHW) address space would correspond to a SoC level memory map.  Is it reasonable to expect that something like `Register(FFixedHW, 64, 0, 0x1000_0000_0000_000C, QWord)` in Appendix B would correspond to some physical address in an SoC's memory map?

**Comment by jones-drew** [comment]
Closing this old issue as it was clarified on the PRS mailing list, https://lists.riscv.org/g/tech-prs/message/839
